#!/bin/bash

#Start selenium server manually: java -jar /usr/local/bin/selenium-server-standalone-2.37.0.jar
#Execute database to have a default state for the tests.
cd module/Application/test
phpunit
cd ../../Problem/test
phpunit
cd ../../Training/test
phpunit
cd ../../Group/test
phpunit
cd ../../Solution/test
phpunit

