<?php
$title = 'Crear Grupo de Entrenamiento';
$this->headTitle($title);
$form->prepare();
?>

<div class="content">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('training_id'));
    ?>
    <table>	
        <tr>
            <td valign="mid"><label for="training_name">Nombre</label></td>
            <td><?php echo $this->formInput($form->get('training_name')); ?></td>
        </tr>
    </table>

    <?php
    echo $this->formSubmit($form->get('submit'));
    ?>
    <a href="<?php echo $this->url('application', array('action' => 'index',)); ?>" class="button">Cancelar</a>
    <?php
    echo $this->form()->closeTag();
    ?> 
</div>