<?php
namespace Group\Form;

use Zend\Form\Form;
use Zend\Form\Element;

$title = 'Grupos';
$this->headTitle($title);
?>
<div class="content">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <div class="nicetable" style="margin-top: 20px;">
        <table>
            <tr>
                <td>ID Grupo</td>
                <td>ID Problema</td>
                
            </tr>
           
        </table>
    </div>	
</div>

