<?php
$title = 'Grupos';
$this->headTitle($title);
?>
<div class="content">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <div class="nicetable" style="margin-top: 20px;">
        <table>
            <tr>
                <td>ID</td>
                <td>Grupo</td>
                <td>Creador</td>
            </tr>
            <?php foreach ($groups as $group) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($group->group_id); ?></td>
                    <td>
                        <a href="<?php echo $this->url('group', array('action' => 'edit', 'id' => $group->group_id)); ?>"><?php echo $this->escapeHtml($group->group_name); ?></a>
                    </td>
                    <td><?php echo $this->escapeHtml($group->name . ' ' . $group->lastname); ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>	
</div>

