<?php
$title = 'Editar Entrenamiento';
$this->headTitle($title);

$form->setAttribute('action', $this->url('group', array('action' => 'training', 'id' => $id)));
$form->prepare();
?>
<div class="content">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('training_id'));
    ?>
    <table>	      
        <tr>
            <td valign="mid"><label for="training_name">Agregar nuevo problema</label></td>
            <td><?php echo $this->formInput($form->get('problem_id')); ?></td>
            <td><?php echo $this->formSubmit($form->get('addProblem')); ?></td>
        </tr>
    </table>

    <div class="nicetable" style="margin-top: 20px;">
        <table>
            <tr>
                <td>ID Grupo</td>
                <td>ID Problema</td>

            </tr>
            <?php foreach ($problems as $group) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($group->problem_name); ?></td>
                    <td><?php echo $this->escapeHtml($group->problem_id); ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>

    <a href="<?php echo $this->url('group', array('action' => 'displaytrainings',)); ?>" class="button">Volver</a>
    <?php
    echo $this->form()->closeTag();
    ?>
</div>