<?php
$title = 'Proponer Problema';
$this->headTitle($title);

$form->setAttribute('action', $this->url('problem', array('action' => 'add')));
$form->prepare();
?>
<div class="content">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('problem_id'));
    ?>
    <center>
        <table>
            <tr>
                <td><label for="problem_name">Nombre</label></td>
                <td><?php echo $this->formInput($form->get('problem_name')); ?></td>
            </tr>
            <tr>
                <td/><td><?php echo $this->formElementErrors($form->get('problem_name')); ?></td>
            </tr>
            <tr>
                <td><label for="author">Autor</label></td>
                <td><?php echo $this->formInput($form->get('author')); ?></td>
            </tr>
            <tr>
                <td/><td><?php echo $this->formElementErrors($form->get('author')); ?></td>
            </tr>
        </table>
    </center>

    <label for="problem_description">Descripcion</label><br/>
    <?php echo $this->formTextarea($form->get('problem_description')); ?><br/>
    <?php echo $this->formElementErrors($form->get('problem_description')); ?><br/>

    <label for="is_simple">Tipo</label><br/>
    <?php echo $this->formRadio($form->get('is_simple')); ?> <br/>

    <label>Archivos de Validacion</label><br/>
    <center>
        <table>
            <tr>
                <td><label for="fileIn">Entrada</label></td>
                <td><?php echo $this->formFile($form->get('fileIn')); ?></td>
                <td><?php echo $this->formElementErrors($form->get('fileIn')); ?></td>
            </tr>
            <tr>
                <td> <label for="fileOut">Salida</label></td>
                <td><?php echo $this->formFile($form->get('fileOut')); ?></td>
                <td><?php echo $this->formElementErrors($form->get('fileOut')); ?></td>
            </tr>
        </table>
    </center>
    
    <label for="compareType">Comparacion</label></br>
    <?php echo $this->formRadio($form->get('compare_type')); ?><br/>

    <?php
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    ?>   
</div>