<?php

$title = 'Problemas Existentes';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($problems as $problem) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($problem->problem_id); ?></td>
            <td><?php echo $this->escapeHtml($problem->problem_name); ?></td>
            <td>
            </td>
        </tr>
    <?php endforeach; ?>
</table>