<?php
$title = 'Problemas Disponibles';
$this->headTitle($title);
?>
<div class="content">
    <h1><?php echo $this->escapeHtml($title); ?></h1>        
    <div class="nicetable" style="margin-top: 20px;">
        <table>
            <tr>
                <td>ID</td>
                <td>Name</td>
                <td>Author</td>
            </tr>
            <?php foreach ($problems as $problem) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($problem->problem_id); ?></td>
                    <td>
                        <a href="<?php echo $this->url('problem', array('action' => 'view', 'id' => $problem->problem_id)); ?>"><?php echo $this->escapeHtml($problem->problem_name); ?></a>
                    </td>
                    <td><?php echo $this->escapeHtml($problem->author); ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>