<?php
$title = 'Crear Grupo de Entrenamiento';
$this->headTitle($title);
$form->prepare();
?>

<div class="content">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('training_id'));
    ?>
    <table>	
        <tr>
            <td valign="mid"><label for="training_name">Nombre</label></td>
            <td><?php echo $this->formInput($form->get('training_name')); ?></td>
            <td><?php echo $this->formElementErrors($form->get('training_name')); ?></td>
        </tr>
        <tr>
            <td valign="mid"><label for="start_date">Fecha de inicio</label></td>
            <td><?php echo $this->formDate($form->get('start_date')); ?></td>
            <td><?php echo $this->formElementErrors($form->get('start_date')); ?></td>
        </tr>
        <tr>
        <tr>
            <td valign="mid"><label for="start_time">Hora de inicio</label></td>
            <td><?php echo $this->formTime($form->get('start_time')); ?></td>
            <td><?php echo $this->formElementErrors($form->get('start_time')); ?></td>
        </tr>
        <tr>
            <td valign="mid"><label for="end_date">Fecha de fin</label></td>
            <td><?php echo $this->formDate($form->get('end_date')); ?></td>
            <td><?php echo $this->formElementErrors($form->get('end_date')); ?></td>
        </tr>
        <tr>
            <td valign="mid"><label for="end_time">Hora de fin</label></td>
            <td><?php echo $this->formTime($form->get('end_time')); ?></td>
            <td><?php echo $this->formElementErrors($form->get('end_time')); ?></td>
        </tr>
    </table>

    <?php
    echo $this->formSubmit($form->get('submit'));
    ?>
    <a href="<?php echo $this->url('application', array('action' => 'index',)); ?>" class="button">Cancelar</a>
    <?php
    echo $this->form()->closeTag();
    ?> 
</div>