<?php
$title = 'Entrenamientos';
$this->headTitle($title);

function getFormattedDate($date) {
    $phpdate = strtotime($date);
    return date('Y-m-d', $phpdate);
}

function getFormattedTime($time) {
    $phpdate = strtotime($time);
    return date('H:i', $phpdate);
}
?>
<div class="content">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <div class="nicetable" style="margin-top: 20px;">
        <table>
            <tr>
                <td>ID</td>
                <td>Nombre</td>
                <td>Creador</td>
                <td>Inicio</td>
                <td>Fin</td>
            </tr>
            <?php foreach ($trainings as $training) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($training->training_id); ?></td>
                    <td>
                        <a href="<?php echo $this->url('training', array('action' => 'edit', 'id' => $training->training_id)); ?>"><?php echo $this->escapeHtml($training->training_name); ?></a>
                    </td>
                    <td><?php echo $this->escapeHtml($training->training_owner); ?></td>
                    <td><?php echo $this->escapeHtml(getFormattedDate($training->start_date) . ' ' . getFormattedTime($training->start_time)); ?></td>
                    <td><?php echo $this->escapeHtml(getFormattedDate($training->end_date) . ' ' . getFormattedTime($training->end_time)); ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>	
</div>

