<aside>
    <section>
        <h2>Juez Virtual</h2>
        <ul>
            <li><a href="/problem">Problemas Disponibles</a></li>
            <li><a href="/problem/add">Proponer Problema</a></li>
            <li><a href="/solution">Soluciones en Ejecucion</a></li>
            <li><a href="/solution/add">Proponer Solucion</a></li>
            <li><a href="/group">Grupos Disponibles</a></li>
            <li><a href="/group/create">Crear Grupo</a></li>
            <li><a href="/training">Entrenamientos Disponibles</a></li>
            <li><a href="/training/create">Crear Entrenamiento</a></li>
        </ul>
    </section>
 
</aside>