<aside>
    <section>
        <h2>Usuario</h2>

        <ul>
            <li><a href="#">Login</a></li>
            <li><a href="#">Register</a></li>
        </ul>
    </section>

    <section>
        <h2>Inicio</h2>

        <ul>
            <li><a href="#">Inicio</a></li>           
        </ul>
    </section>

    <section>
        <h2>Juez Virtual</h2>
        <ul>
            <li><a href="#">Proponer problema</a></li>
            <li><a href="#">Proponer solucion</a></li>
        </ul>
    </section>
 
</aside>