<?php
$title = 'Proponer Solucion';
$this->headTitle($title);

$form->setAttribute('action', $this->url('solution', array('action' => 'add')));
$form->prepare();
?>

<div class="content">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('solution_id'));
    ?>
    <h2>Datos Principales</h2>
    <table>	
        <tr>
            <td valign="mid"><label for="problem_id">ID Problema</label></td>
            <td><?php echo $this->formInput($form->get('problem_id')); ?></td>
        </tr>
        <tr>
            <td/>
            <td><?php echo $this->formElementErrors($form->get('problem_id')); ?></td>
        </tr>
        <tr>
            <td valign="mid"><label for="solution_language">Lenguaje</label></td>
            <td>
                <div class="styled-select">
                    <?php echo $this->formSelect($form->get('solution_language')); ?>
                </div>
            </td>
        </tr>
        <tr>
            <td/>
            <td><?php echo $this->formElementErrors($form->get('solution_language')); ?></td>
        </tr>

        <tr>
            <td valign="top"><label for="solution_source_file">Archivo de solucion</label></td>
            <td><?php echo $this->formFile($form->get('solution_source_file')); ?></td>
        </tr>
        <tr>
            <td/>
            <td><?php echo $this->formElementErrors($form->get('solution_source_file')); ?></td>
        </tr>
    </table>

    <?php
    echo $this->formSubmit($form->get('submit'));
    ?>
    <a href="<?php echo $this->url('application', array('action' => 'index',)); ?>" class="button">Cancelar</a>
    <?php
    echo $this->form()->closeTag();
    ?>   
</div>