<?php
$title = 'Proponer Solucion';
$this->headTitle($title);

$form->setAttribute('action', $this->url('solution', array('action' => 'add')));
$form->prepare();
?>

<div class="content">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('solution_id'));
    ?>
    <h2>Datos Principales</h2>
    <table>	
        <tr>
            <td valign="mid"><label for="problem_id">ID Problema</label></td>
            <td><?php echo $this->formInput($form->get('problem_id')); ?></td>
        </tr>
        <tr>
            <td/>
            <td><?php echo $this->formElementErrors($form->get('problem_id')); ?></td>
        </tr>
        <tr>
            <td valign="mid"><label for="language">Lenguaje</label></td>
            <td><?php echo $this->formSelect($form->get('language')); ?></td>
        </tr>
        <tr>
            <td/>
            <td><?php echo $this->formElementErrors($form->get('language')); ?></td>
        </tr>
        
        <tr>
            <td valign="top"><label for="solution_source">Archivo de solucion</label></td>
            <td><?php echo $this->formFile($form->get('solution_source')); ?></td>
        </tr>
        <tr>
            <td/>
            <td><?php echo $this->formElementErrors($form->get('solution_source')); ?></td>
        </tr>
    </table>
    
    <input type="button" name="cancel" class="button" onsubmit="" value="Cancelar">

    <?php
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    ?>   
</div>