<?php
$title = 'Solucion: ' . $solution->solution_id;
$this->headTitle($title);
?>

<div class="content">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <table>	
        <tr>
            <td><label>Fecha</label></td>
            <td>
                <?php echo $this->escapeHtml($solution->solution_date) ?>
            </td>
        </tr>
        <tr>
            <td><label>Veredicto</label></td>
            <td>
                <?php echo $this->escapeHtml($solution->status) ?>
            </td>
        </tr>
        <tr>
            <td><label>Lenguaje</label></td>
            <td>
                <?php echo $this->escapeHtml($solution->solution_language) ?>
            </td>
        </tr>
        <tr>
            <td><label>Puntaje</label></td>
            <td>
                <?php echo $this->escapeHtml($solution->grade) ?>
            </td>
        </tr>
        <tr>
            <td><label>Tiempo de Ejecucion</label></td>
            <td>
                <?php echo $this->escapeHtml($solution->runtime) ?>
            </td>
        </tr>
        <tr>
            <td><label>Memoria Usada</label></td>
            <td>
                <?php echo $this->escapeHtml($solution->used_memory) ?>
            </td>
        </tr>
        <tr>
            <td><label>Errores</label></td>
            <td>
                <?php echo $this->escapeHtml($solution->error_message) ?>
            </td>
        </tr>
    </table>
    <a href="<?php echo $this->url('solution', array('action' => 'index',)); ?>" class="button">Volver</a>
</div>