<?php
$title = 'Soluciones';
$this->headTitle($title);
?>

<div class="content">
    <h1><?php echo $this->escapeHtml($title); ?></h1>        
    <center>
        <div style="margin-top: 20px;">
            <table class="table-bordered"  style="width: 70%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Date</th>
                        <th>User</th>
                        <th>Grade</th>
                        <th>Result</th>
                        <th>Time</th>
                        <th>Memory</th>
                        <th>Language</th>
                    </tr>
                </thead>
                <?php foreach ($solutions as $solution) : ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($solution->solution_id); ?></td>
                        <td><?php echo $this->escapeHtml($solution->solution_date); ?></td>
                        <td><?php echo $this->escapeHtml($solution->user_user_id); ?></td>
                        <td><?php echo $this->escapeHtml($solution->grade); ?></td>
                        <td>
                            <a href="<?php echo $this->url('solution', array('action' => 'display', 'id' => $solution->solution_id)); ?>"><?php echo $this->escapeHtml($solution->status); ?></a>
                        </td>
                        <td><?php echo $this->escapeHtml($solution->runtime); ?></td>
                        <td><?php echo $this->escapeHtml($solution->used_memory); ?></td>                   
                        <td><?php echo $this->escapeHtml($solution->solution_language); ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </center>
</div>