<div class="content">
    <p>La Olimpiada Internacional de Informática es una más de las Olimpiadas Internacionales de Ciencias, que tiene como objetivo potenciar el aprendizaje de la informática en alumnos de secundaria y preparatoria (nivel medio y medio superior).</p>
    <p>Los problemas de esta competición están orientados a los algoritmos. No se requiere mucho conocimiento en cuanto al uso del API, pero sí habilidad en la resolución de problemas y en el diseño de algoritmos. </p>
    <p>Al concurso asisten 4 seleccionados de cada uno de los más de 80 países que participan. Los 4 seleccionados son elegidos de entre miles de estudiantes que participan en las olimpiadas regionales y nacionales en sus países.</p>
</div>